apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Exchange-Set-Service
  description: The Exchange Set Service generates S-63 exchange sets for AVCS
  annotations:
    github.com/project-slug: ukho/exchange-set-service
spec:
  type: service
  lifecycle: alpha
  owner: rockydevnet
  system: ADDS
  providesApis:
    - Exchange-Set-Service
  consumesApis:
    - File-Share-Service
    - Sales-Catalogue-Service
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: Exchange-Set-Service
  description: Exchange Set Service API
spec:
  type: openapi
  lifecycle: alpha
  owner: rockydevnet
  system: ADDS
  definition:
    $text: ./exchangeSetService_OpenApi_definition.yaml asd asd 
