using Microsoft.Extensions.Configuration;
using NUnit.Framework;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Threading.Tasks;
using UKHO.ExchangeSetService.API.FunctionalTests.Helper;
using UKHO.ExchangeSetService.API.FunctionalTests.Models;

namespace UKHO.ExchangeSetService.API.FunctionalTests.FunctionalTests
{
    public class ReadMeFileCheckandVerification
    {
        private ExchangeSetApiClient ExchangeSetApiClient { get; set; }
        private TestConfiguration Config { get; set; }
        private DataHelper DataHelper { get; set; }

        private readonly string sinceDateTime = DateTime.Now.AddDays(-10).ToString("ddd, dd MMM yyyy HH':'mm':'ss 'GMT'", CultureInfo.InvariantCulture);
        private string EssJwtToken { get; set; }
        public ProductIdentifierModel ProductIdentifierModel { get; set; }

        private readonly IConfiguration Configuration;

        public ReadMeFileCheckandVerification(IConfiguration Configuration)
        {
            this.Configuration = Configuration;
        }


        [SetUp]
        public async Task SetupAsync()
        {
            Config = new TestConfiguration();
            ExchangeSetApiClient = new ExchangeSetApiClient(Config.EssBaseAddress);
            ProductIdentifierModel = new ProductIdentifierModel();
            AuthTokenProvider authTokenProvider = new AuthTokenProvider();
            EssJwtToken = await authTokenProvider.GetEssToken();
            DataHelper = new DataHelper();
        }

        /// <summary>
        /// Generate file path location
        /// </summary>
        /// <param name="homeDirectoryPath">Home directory</param>
        /// <param name="batchId">Batch Id generated by exchange set</param>
        /// <returns></returns>
        public string GenerateFilePath(string homeDirectoryPath,string batchId)
        {
            var filePath = Path.Combine(homeDirectoryPath, DateTime.UtcNow.ToString("ddMMMyyyy"), batchId, Config.ExchangeSetFileFolder, Config.EncRootFolder);
            return filePath;
        }

       
        [Test]
        public async Task WhenICallTheApiWithAValidRFC1123DateTime_ThenAReadMeFileWithContentIsCreated()
        {
            var apiResponse = await ExchangeSetApiClient.GetExchangeSetBasedOnDateTimeAsync(sinceDateTime, accessToken: EssJwtToken);
            Assert.AreEqual(200, (int)apiResponse.StatusCode, $"Incorrect status code is returned {apiResponse.StatusCode}, instead of the expected 200.");

            var batchId = await apiResponse.GetBatchId();
            string homeDirectoryPath = Configuration["HOME"];

            var filePath = GenerateFilePath(homeDirectoryPath, batchId);
            
            bool checkIfFileExistInDirectory =await FileCheck.CheckIfFileExistAndVerify(filePath, Config.ReadMeFileName);
            
            Assert.IsTrue(checkIfFileExistInDirectory);
        }

        [Test]
        public async Task WhenICallTheApiWithAValidProductIdentifiers_ThenAReadMeFileWithContentIsCreated()
        {
            var apiResponse = await ExchangeSetApiClient.GetProductIdentifiersDataAsync(DataHelper.GetProductIdentifierData(), accessToken: EssJwtToken);
            Assert.AreEqual(200, (int)apiResponse.StatusCode, $"Incorrect status code is returned {apiResponse.StatusCode}, instead of the expected status 200.");

            var batchId = await apiResponse.GetBatchId();
            string homeDirectoryPath = Configuration["HOME"];

            var filePath = GenerateFilePath(homeDirectoryPath, batchId);

            bool checkIfFileExistInDirectory = await FileCheck.CheckIfFileExistAndVerify(filePath, Config.ReadMeFileName);
            
            Assert.IsTrue(checkIfFileExistInDirectory);
        }

        [Test]
        public async Task WhenICallTheApiWithInvalidProductIdentifiers_ThenAReadMeFileWithContentIsCreated()
        {
            ProductIdentifierModel.ProductIdentifier = new List<string>() { "GB123789" };

            var apiResponse = await ExchangeSetApiClient.GetProductIdentifiersDataAsync(ProductIdentifierModel.ProductIdentifier, accessToken: EssJwtToken);
            Assert.AreEqual(200, (int)apiResponse.StatusCode, $"Incorrect status code is returned {apiResponse.StatusCode}, instead of the expected status 200.");

            var batchId = await apiResponse.GetBatchId();
            string homeDirectoryPath = Configuration["HOME"];

            var filePath = GenerateFilePath(homeDirectoryPath, batchId);

            bool checkIfFileExistInDirectory = await FileCheck.CheckIfFileExistAndVerify(filePath, Config.ReadMeFileName);
            
            Assert.IsTrue(checkIfFileExistInDirectory);
        }

        [Test]
        public async Task WhenICallTheApiWithAValidProductVersion_ThenAReadMeFileWithContentIsCreated()
        {
            List<ProductVersionModel> ProductVersionData = new List<ProductVersionModel>();

            ProductVersionData.Add(DataHelper.GetProductVersionModelData("DE416080", 9, 6));           

            var apiResponse = await ExchangeSetApiClient.GetProductVersionsAsync(ProductVersionData, accessToken: EssJwtToken);
            Assert.AreEqual(200, (int)apiResponse.StatusCode, $"Incorrect status code {apiResponse.StatusCode}  is  returned, instead of the expected 200.");

            var batchId = await apiResponse.GetBatchId();
            string homeDirectoryPath = Configuration["HOME"];

            var filePath = GenerateFilePath(homeDirectoryPath, batchId);

            bool checkIfFileExistInDirectory = await FileCheck.CheckIfFileExistAndVerify(filePath, Config.ReadMeFileName);
            
            Assert.IsTrue(checkIfFileExistInDirectory);
        }

        [Test]
        public async Task WhenICallTheApiWithValidAndInvalidProductVersion_ThenAReadMeFileWithContentIsCreated()
        {
            List<ProductVersionModel> ProductVersionData = new List<ProductVersionModel>();

            ProductVersionData.Add(DataHelper.GetProductVersionModelData("DE416080", 9, 5));
            ProductVersionData.Add(DataHelper.GetProductVersionModelData("GB123789", 1, 0));

            var apiResponse = await ExchangeSetApiClient.GetProductVersionsAsync(ProductVersionData, accessToken: EssJwtToken);
            Assert.AreEqual(200, (int)apiResponse.StatusCode, $"Incorrect status code {apiResponse.StatusCode} is returned, instead of the expected 200.");

            var batchId = await apiResponse.GetBatchId();
            string homeDirectoryPath = Configuration["HOME"];

            var filePath = GenerateFilePath(homeDirectoryPath, batchId);

            bool checkIfFileExistInDirectory = await FileCheck.CheckIfFileExistAndVerify(filePath, Config.ReadMeFileName);
            
            Assert.IsTrue(checkIfFileExistInDirectory);
        }

        [Test]
        public async Task WhenICallTheApiWithProductVersionNotAvailable_ThenAReadMeFileWithContentIsCreated()
        {
            List<ProductVersionModel> ProductVersionData = new List<ProductVersionModel>();

            ProductVersionData.Add(DataHelper.GetProductVersionModelData("DE416080", 100, 5));

            var apiResponse = await ExchangeSetApiClient.GetProductVersionsAsync(ProductVersionData, accessToken: EssJwtToken);
            Assert.AreEqual(200, (int)apiResponse.StatusCode, $"Incorrect status code {apiResponse.StatusCode} is returned, instead of the expected 200.");

            var batchId = await apiResponse.GetBatchId();
            string homeDirectoryPath = Configuration["HOME"];

            var filePath = GenerateFilePath(homeDirectoryPath, batchId);

            bool checkIfFileExistInDirectory = await FileCheck.CheckIfFileExistAndVerify(filePath, Config.ReadMeFileName);
            
            Assert.IsTrue(checkIfFileExistInDirectory);
        }
    }
}
