parameters:
- name: Environment
  type: string
- name: AzureSubscription
  type: string
- name: LiveOrNonLive
  type: string
  default: "NonLive"  
- name: ContinueEvenIfResourcesAreGettingDestroyed
  type: boolean
  default: false
- name: Container
  type: string
- name: RunTests
  type: boolean
  default: false
- name: pathSuffix
  type: string
  default: ""
- name: v2Modifier
  type: string
  default: ""

jobs:
- deployment: DeployApp${{parameters.v2Modifier}}
  timeoutInMinutes: 75
  displayName: "${{parameters.Environment}}${{parameters.pathSuffix}} - deploy terraform and dotnet App"
  environment: "Ess-${{parameters.Environment}}"
  pool: $(DeploymentPool)
  container: ${{parameters.Container}}
  workspace:
    clean: all
  variables:
    - group: "ESS-Deployment-Variables-${{parameters.Environment}}"
    - group: "ESS-${{parameters.Environment}}${{parameters.v2Modifier}}-Variables"
    - name: "ESSAzureADConfiguration.ClientId"
      value: $(ESSClientId)
    - name: "ESSAzureADConfiguration.TenantId"
      value: $(TenantId)
    - name: "EssAuthorizationConfiguration.TenantId"
      value: $(TenantId)
    - name: "EssAuthorizationConfiguration.AutoTestClientId"
      value: $(AutoTestClientId_Authed)
    - name: "EssAuthorizationConfiguration.AutoTestClientSecret"
      value: $(AutoTestClientSecret_Authed)
    - name: "EssAuthorizationConfiguration.EssClientId"
      value: $(ESSClientId)
    - name: "EssAuthorizationConfiguration.AutoTestClientIdNoAuth"
      value: $(AutoTestClientId_NoAuth)
    - name: "EssAuthorizationConfiguration.AutoTestClientSecretNoAuth"
      value: $(AutoTestClientSecret_NoAuth)
    - name: "AzureAdB2CTestConfiguration.ClientSecret"
      value: $(AUTOTEST-ESS-SECRET)
  strategy:
    runOnce:
      deploy:
        steps:
          - checkout: none

          - download: current
            displayName: Download terraformartifact
            artifact: terraformartifact

          - download: current
            displayName: Download ExchangeSetService
            artifact: ExchangeSetService

          - download: current
            displayName: Download ExchangeSetServiceWebAPI
            artifact: ExchangeSetServiceWebAPI

          - template: continuous-deployment${{parameters.pathSuffix}}.yml
            parameters:
              ContinueEvenIfResourcesAreGettingDestroyed: ${{ parameters.ContinueEvenIfResourcesAreGettingDestroyed }}
              AzureSubscription: ${{parameters.AzureSubscription}}

          - template: continuous-deployment-apim${{parameters.pathSuffix}}.yml
            parameters:
              ContinueEvenIfResourcesAreGettingDestroyed: ${{ parameters.ContinueEvenIfResourcesAreGettingDestroyed }}
              AzureSubscription: "UKHO-APIM-SOLAS-${{parameters.LiveOrNonLive}}"
              TerraformKeyVault: $(APIM_TERRAFORM_KEYVAULT)
              APIMResourceGroup: $(APIM_RESOURCE_GROUP_NAME)
              APIMServiceInstance: $(APIM_SERVICE_NAME)
              tfstateStorageAccountName: $(APIM_TFSTATE_STORAGE_ACCOUNT_NAME)