parameters:
- name: Environment
  type: string
- name: AzureSubscription
  type: string
- name: LiveOrNonLive
  type: string
  default: "NonLive"  
- name: ContinueEvenIfResourcesAreGettingDestroyed
  type: boolean
  default: false
- name: Container
  type: string
- name: RunTests
  type: boolean
  default: true

jobs:
# - deployment: DeployApimSolas
#   displayName: "${{parameters.Environment}} - deploy SOLAS APIM"
#   environment: "Ess-${{parameters.Environment}}"
#   pool: $(DeploymentPool)
#   container: ${{parameters.Container}}
#   workspace:
#     clean: all
#   variables:
#     - group: "ESS-Deployment-Variables-${{parameters.Environment}}"
#     - group: "ESS-${{parameters.Environment}}-Variables"
#     - group: "ESS-${{parameters.Environment}}-APIM-SOLAS-Variables"
#   strategy:
#     runOnce:
#       deploy:
#         steps:
#           - template: continuous-deployment-apim.yml
#             parameters:
#               ContinueEvenIfResourcesAreGettingDestroyed: ${{ parameters.ContinueEvenIfResourcesAreGettingDestroyed }}
#               AzureSubscription: "UKHO-APIM-SOLAS-${{parameters.LiveOrNonLive}}"
#               TerraformKeyVault: $(APIM_SOLAS_TERRAFORM_KEYVAULT)
#               APIMResourceGroup: $(APIM_SOLAS_RESOURCE_GROUP_NAME)
#               APIMServiceInstance: $(APIM_SOLAS_SERVICE_NAME)
#               tfstateStorageAccountRG: $(APIM_SOLAS_RESOURCE_GROUP_NAME)
#               tfstateStorageAccountName: $(APIM_SOLAS_TFSTATE_STORAGE_ACCOUNT_NAME)
#               SetLinkRewriteNewToOld: false
#               UseNewTfplanName: true

- deployment: DeployApp
 # dependsOn: DeployApimSolas
  timeoutInMinutes: 75
  displayName: "${{parameters.Environment}} - deploy terraform and dotnet App"
  environment: "Ess-${{parameters.Environment}}"
  pool: $(DeploymentPool)
  container: ${{parameters.Container}}
  workspace:
    clean: all
  variables:
    - group: "ESS-Deployment-Variables-${{parameters.Environment}}"
    - group: "ESS-${{parameters.Environment}}-Variables"
    - name: "ESSAzureADConfiguration.ClientId"
      value: $(ESSClientId)
    - name: "ESSAzureADConfiguration.TenantId"
      value: $(TenantId)
    - name: "EssAuthorizationConfiguration.TenantId"
      value: $(TenantId)
    - name: "EssAuthorizationConfiguration.AutoTestClientId"
      value: $(AutoTestClientId_Authed)
    - name: "EssAuthorizationConfiguration.AutoTestClientSecret"
      value: $(AutoTestClientSecret_Authed)
    - name: "EssAuthorizationConfiguration.EssClientId"
      value: $(ESSClientId)
    - name: "EssAuthorizationConfiguration.AutoTestClientIdNoAuth"
      value: $(AutoTestClientId_NoAuth)
    - name: "EssAuthorizationConfiguration.AutoTestClientSecretNoAuth"
      value: $(AutoTestClientSecret_NoAuth)
    - name: "AzureAdB2CTestConfiguration.ClientSecret"
      value: $(AUTOTEST-ESS-SECRET)
  strategy:
    runOnce:
      deploy:
        steps:
          - checkout: self
            submodules: recursive

          # - template: continuous-deployment.yml
          #   parameters:
          #     ContinueEvenIfResourcesAreGettingDestroyed: ${{ parameters.ContinueEvenIfResourcesAreGettingDestroyed }}
          #     AzureSubscription: ${{parameters.AzureSubscription}}

          # - template: continuous-deployment-apim.yml
          #   parameters:
          #     ContinueEvenIfResourcesAreGettingDestroyed: ${{ parameters.ContinueEvenIfResourcesAreGettingDestroyed }}
          #     AzureSubscription: "Fleet Manager dev/Test"
          #     TerraformKeyVault: $(APIM_TERRAFORM_KEYVAULT)
          #     APIMResourceGroup: $(APIM_RESOURCE_GROUP_NAME)
          #     APIMServiceInstance: $(APIM_SERVICE_NAME)
          #     tfstateStorageAccountRG: $(APIM_TFSTATE_STORAGE_ACCOUNT_RG)
          #     tfstateStorageAccountName: $(APIM_TFSTATE_STORAGE_ACCOUNT_NAME)
              
          # - task: DownloadBuildArtifacts@0
          #   displayName: "Download Functional test Artifact"
          #   inputs:
          #     buildType: 'current'
          #     downloadType: 'single'
          #     artifactName: 'functionaltests'
          #     downloadPath: '$(Build.SourcesDirectory)'

          # - task: DownloadBuildArtifacts@0
          #   displayName: "Download Terraform Artifact"
          #   inputs:
          #     buildType: 'current'
          #     downloadType: 'single'
          #     artifactName: 'terraformartifact'
          #     downloadPath: '$(Build.SourcesDirectory)'

          # - task: FileTransform@2
          #   displayName: "File Transform: functionaltests"
          #   inputs:
          #     folderPath: '$(Build.SourcesDirectory)/functionaltests/'
          #     xmlTransformationRules:
          #     jsonTargetFiles: '**/appsettings.json'

          # - task: UseDotNet@2
          #   displayName: 'Use .NET SDK'
          #   inputs:
          #     packageType: sdk
          #     useGlobalJson: true
          #     workingDirectory: '$(Build.SourcesDirectory)'
            
          - task: PowerShell@2
            displayName: 'Set env variables'
            inputs:
              targetType: 'inline'
              script: |
                  echo "##vso[task.setvariable variable=WEB_APP_NAME;isOutput=true]TEST"
                  echo "##vso[task.setvariable variable=RESOURCE_GROUP_NAME;isOutput=true]$TEST"
                 
            name: functionalTestVariables
    # echo "##vso[task.setvariable variable=WEB_APP_NAME;isOutput=true]$(TerraformDeploy.WEB_APP_NAME)"
    #               echo "##vso[task.setvariable variable=RESOURCE_GROUP_NAME;isOutput=true]$(TerraformDeploy.RESOURCE_GROUP_NAME)"
              
          - task: PowerShell@2
            displayName: 'Echo functionalTestVariables'
            inputs:
              targetType: 'inline'
              script: |
                echo "WEB_APP_NAME: $(functionalTestVariables.WEB_APP_NAME)"
                echo "RESOURCE_GROUP_NAME: $(functionalTestVariables.RESOURCE_GROUP_NAME)"

# - job: VarCheck
#   dependsOn: DeployApp
#   variables:
#     - name: WEB_APP_NAME
#       value: $[ dependencies.DeployApp.outputs['functionalTestVariables.WEB_APP_NAME'] ]
#     - name: RESOURCE_GROUP_NAME
#       value: $[ dependencies.DeployApp.outputs['functionalTestVariables.RESOURCE_GROUP_NAME'] ]
#   steps:
#     - task: PowerShell@2
#       displayName: 'Echo functionalTestVariables'
#       inputs:
#         targetType: 'inline'
#         script: |
#           echo "WEB_APP_NAME: $(functionalTestVariables.WEB_APP_NAME)"
#           echo "RESOURCE_GROUP_NAME: $(functionalTestVariables.RESOURCE_GROUP_NAME)"
#     - script: echo $(WEB_APP_NAME)
#     # - script: echo $(WEB_APP_NAME)
#     # - script: echo $(RESOURCE_GROUP_NAME)
#     # - script: echo WEB_APP_NAME $(TerraformDeploy.WEB_APP_NAME)
#     # - script: echo RESOURCE_GROUP_NAME $(TerraformDeploy.RESOURCE_GROUP_NAME)

- deployment: FunctionalTests
  dependsOn: DeployApp
  displayName: "Run Functional Tests"
  environment: "Ess-${{parameters.Environment}}"
  pool: $(DeploymentPool)
  container: ${{parameters.Container}}
  condition: ${{parameters.RunTests}}
  variables:
    - group: "ESS-${{parameters.Environment}}-Variables"
    - group: "ESS-Deployment-Variables-${{parameters.Environment}}"
    - name: WEB_APP_NAME
      value: $(WEB_APP_NAME)
    - name: RESOURCE_GROUP_NAME
      value: $[ dependencies.DeployApp.outputs['functionalTestVariables.RESOURCE_GROUP_NAME'] ]
  strategy:
    runOnce:
      deploy:
        steps:
          - script: echo ${{variables.WEB_APP_NAME}}
          - script: echo ${variables.WEB_APP_NAME}
          - script: echo $(variables.WEB_APP_NAME)


          - template: RunTests.yml
            parameters:
              Environment: ${{parameters.Environment}}
              AzureSubscription: ${{parameters.AzureSubscription}}

